parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
env:
  browser: true
  node: true
rules:
  no-console: error
  prettier/prettier: [error, { endOfLine: auto }]
  '@typescript-eslint/explicit-module-boundary-types': off
